import os
import re
import json

locales_dir = "/Users/raphael/Sites/Siam Visa Production v1/src/locales"

translations = {
    "ar": {
        "meta": {
            "title": "خدماتنا والأسعار لتأشيرات تايلاند | Siam Visa Pro",
            "description": "إعداد الملف بالكامل + التقديم للسفارة. الأسعار والخدمات."
        },
        "hero_title": "خدماتنا والأسعار",
        "hero_subtitle": "إعداد الملف بالكامل + التقديم للسفارة",
        "hero_tagline": "نحن لسنا السفارة، نحن حلفاؤك.",
        "hero_tagline_secondary": "خبرة كاملة لراحة بالك في تايلاند.",
        "custom_support_title": "بحاجة إلى دعم مخصص؟",
        "custom_support_desc": "خبراؤنا متاحون لتحليل ملفك المحدد واقتراح أفضل استراتيجية للاغتراب.",
        "custom_support_btn": "تحدث مع خبير",
        "tier_standard": "أساسي",
        "tier_standard_desc": "ملف كامل + تقديم للسفارة",
        "tier_standard_price": "390 €",
        "tier_express": "سريع 48 ساعة",
        "tier_express_desc": "ملف كامل + تقديم عاجل للسفارة",
        "tier_express_price": "590 €",
        "tier_premium": "مميز",
        "tier_premium_desc": "ملف كامل + تقديم للسفارة + متابعة مستمرة",
        "tier_premium_price": "890 €",
        "btn_start": "ابدأ طلبك",
        "recommended": "موصى به",
        "insurance_title": "بحاجة إلى تأمين سفر؟",
        "insurance_desc": "قد يكون التأمين الصحي مطلوبًا.",
        "insurance_link": "عرض شركائنا في التأمين",
        "pack_feat1": "التحقق من الأهلية + قائمة تحقق مخصصة",
        "pack_feat2": "إعداد/إكمال النماذج",
        "pack_feat3": "مراجعة المستندات (جواز السفر، الصور، الإثبات المالي...)",
        "pack_feat4": "تجميع الملف النهائي",
        "pack_feat5": "التقديم للسفارة/القنصلية + المتابعة",
        "admin_fees_title": "الرسوم الإدارية",
        "admin_fees_subtitle": "تدفع مباشرة للسفارة/القنصلية",
        "admin_fees_visa": "رسوم التأشيرة (تختلف حسب نوع التأشيرة)",
        "admin_fees_center": "رسوم مركز التأشيرات محتملة",
        "options_title": "خيارات إضافية",
        "option_traduction": "ترجمات معتمدة",
        "option_traduction_price": "39–89 € / مستند",
        "option_legalisation": "تصديق / أبوستيل",
        "option_legalisation_price": "49–129 € / مستند",
        "option_assurance": "تأمين سفر متوافق",
        "option_assurance_price": "0 €",
        "option_rdv": "موعد / رحلة تقديم",
        "option_rdv_price": "49–149 €",
        "option_suivi": "تتبع ما بعد التقديم & متابعات",
        "option_suivi_price": "متضمن في المميز، وإلا 49 €",
        "included_title": "محتويات كل باقة",
        "conditions_title": "الشروط",
        "condition1": "رسوم السفارة دائما إضافية (وغير قابلة للاسترداد).",
        "condition2": "تقديم بمرافقة بدلاً من تقديم نيابة عند اللزوم."
    },
    "de": {
        "meta": {
            "title": "Dienstleistungen & Preise Thailand Visum | Siam Visa Pro",
            "description": "Vollständige Aktenbearbeitung + Einreichung bei der Botschaft. Standard, Express und Premium Pakete."
        },
        "hero_title": "Unsere Dienstleistungen & Preise",
        "hero_subtitle": "Vollständige Aktenbearbeitung + Einreichung bei der Botschaft",
        "hero_tagline": "Wir sind nicht die Botschaft, wir sind Ihre Verbündeten.",
        "hero_tagline_secondary": "Umfassende Expertise für Ihre Sorgenfreiheit in Thailand.",
        "custom_support_title": "Benötigen Sie maßgeschneiderte Unterstützung?",
        "custom_support_desc": "Unsere Experten analysieren Ihre Akte für die beste Expatriierungsstrategie.",
        "custom_support_btn": "Mit einem Experten sprechen",
        "tier_standard": "Standard",
        "tier_standard_desc": "Vollständige Akte + Einreichung",
        "tier_standard_price": "390 €",
        "tier_express": "Express 48h",
        "tier_express_desc": "Vollständige Akte + dringende Einreichung",
        "tier_express_price": "590 €",
        "tier_premium": "Premium",
        "tier_premium_desc": "Akte + Einreichung + verstärkte Nachverfolgung",
        "tier_premium_price": "890 €",
        "btn_start": "Ihren Antrag starten",
        "recommended": "Empfohlen",
        "insurance_title": "Reiseversicherung benötigt?",
        "insurance_desc": "Eine Krankenversicherung über 100k USD kann erforderlich sein.",
        "insurance_link": "Versicherungspartner ansehen",
        "pack_feat1": "Mappe prüfen + personalisierte Checkliste",
        "pack_feat2": "Ausfüllen der Formulare",
        "pack_feat3": "Überprüfung & Konformität der Unterlagen",
        "pack_feat4": "Endgültige Aktenzusammenstellung",
        "pack_feat5": "Botschaftseinreichung + Nachverfolgung",
        "admin_fees_title": "Verwaltungsgebühren",
        "admin_fees_subtitle": "Direkt an die Botschaft zu zahlen",
        "admin_fees_visa": "Visagebühren der Regierung",
        "admin_fees_center": "Gebühren für Visazentrum",
        "options_title": "Zusätzliche Optionen",
        "option_traduction": "Beglaubigte Übersetzungen",
        "option_traduction_price": "39–89 € / Dokument",
        "option_legalisation": "Legalisierung / Apostille",
        "option_legalisation_price": "49–129 € / Dokument",
        "option_assurance": "Konforme Reiseversicherung",
        "option_assurance_price": "0 €",
        "option_rdv": "Termin / Einreichungsfahrt",
        "option_rdv_price": "49–149 €",
        "option_suivi": "Nachverfolgung",
        "option_suivi_price": "Im Premium enthalten, sonst 49 €",
        "included_title": "Enthalten in Paketen",
        "conditions_title": "Bedingungen",
        "condition1": "Botschaftsgebühren zzgl.",
        "condition2": "Begleitete Einreichung bei Anwesenheitspflicht."
    },
    "es": {
        "meta": {
            "title": "Servicios y Precios Visado Tailandia | Siam Visa Pro",
            "description": "Preparación completa + presentación en la embajada. Paquetes estándar, exprés y premium."
        },
        "hero_title": "Nuestros Servicios y Precios",
        "hero_subtitle": "Preparación completa + presentación en la embajada",
        "hero_tagline": "No somos la embajada, somos tus aliados.",
        "hero_tagline_secondary": "Experiencia para tu tranquilidad en Tailandia.",
        "custom_support_title": "¿Apoyo personalizado?",
        "custom_support_desc: ": "Los expertos analizan tu expediente para la mejor estrategia.",
        "custom_support_btn": "Hablar con un experto",
        "tier_standard": "Estándar",
        "tier_standard_desc": "Expediente completo + embajada",
        "tier_standard_price": "390 €",
        "tier_express": "Exprés 48h",
        "tier_express_desc": "Expediente + urgente embajada",
        "tier_express_price": "590 €",
        "tier_premium": "Premium",
        "tier_premium_desc": "Expediente + embajada + seguimiento",
        "tier_premium_price": "890 €",
        "btn_start": "Iniciar solicitud",
        "recommended": "Recomendado",
        "insurance_title": "¿Seguro de viaje?",
        "insurance_desc": "Podría exigirse seguro médico (según visado).",
        "insurance_link": "Socios de seguros",
        "pack_feat1": "Revisión elegibilidad + control",
        "pack_feat2": "Formularios lista",
        "pack_feat3": "Documentos (pasaporte, dinero, etc)",
        "pack_feat4": "Ensamblaje del expediente",
        "pack_feat5": "Representación y/o presentación embajada",
        "admin_fees_title": "Tarifas administrativas",
        "admin_fees_subtitle": "Pagas directamente embajada/consulado",
        "admin_fees_visa": "Tarifas oficiales de visa",
        "admin_fees_center": "Posibles tarifas centro",
        "options_title": "Opciones extra",
        "option_traduction": "Traducciones",
        "option_traduction_price": "39–89 € / doc",
        "option_legalisation": "Apostilla",
        "option_legalisation_price": "49–129 € / doc",
        "option_assurance": "Seguro de viaje",
        "option_assurance_price": "0 €",
        "option_rdv": "Viaje o cita",
        "option_rdv_price": "49–149 €",
        "option_suivi": "Seguimiento",
        "option_suivi_price": "Premium, o 49 €",
        "included_title": "Incluido en paquetes",
        "conditions_title": "Condiciones",
        "condition1": "Tarifas consulares no regresan.",
        "condition2": "Asistencia local en embajadas que solicitan cita."
    },
    "it": {
        "meta": {
            "title": "I Nostri Servizi e Prezzi Visto Thailandia | Siam Visa Pro",
            "description": "Preparazione pratica + presentazione all'ambasciata. Pacchetti Standard, Express e Premium."
        },
        "hero_title": "I Nostri Servizi e Prezzi",
        "hero_subtitle": "Preparazione completa della pratica + presentazione all'ambasciata",
        "hero_tagline": "Non siamo l'ambasciata, siamo i tuoi alleati.",
        "hero_tagline_secondary": "Competenza completa per la tua tranquillità.",
        "custom_support_title": "Supporto su misura?",
        "custom_support_desc": "I nostri esperti analizzano il caso specifico e la strategia di espatrio.",
        "custom_support_btn": "Parla con un esperto",
        "tier_standard": "Standard",
        "tier_standard_desc": "Pratica completa + presentazione",
        "tier_standard_price": "390 €",
        "tier_express": "Express 48h",
        "tier_express_desc": "Pratica completa + urgente presentazione",
        "tier_express_price": "590 €",
        "tier_premium": "Premium",
        "tier_premium_desc": "Pratica + presentazione + monitoraggio",
        "tier_premium_price": "890 €",
        "btn_start": "Inizia la pratica",
        "recommended": "Consigliato",
        "insurance_title": "Assicurazione di viaggio?",
        "insurance_desc": "Richiesta copertura minima in alcune liste.",
        "insurance_link": "Partner assicurativi",
        "pack_feat1": "Controllo documentazione idoneità",
        "pack_feat2": "Form da riempire",
        "pack_feat3": "Conformità allegati",
        "pack_feat4": "Faldone completo",
        "pack_feat5": "Invio e attesa per il visto",
        "admin_fees_title": "Spese amministrative",
        "admin_fees_subtitle": "Dal governo / Ambasciata",
        "admin_fees_visa": "Prezzo ufficiale",
        "admin_fees_center": "Gestione centro locale",
        "options_title": "Opzioni aggiuntive",
        "option_traduction": "Traduzioni giurate",
        "option_traduction_price": "39–89 € / doc",
        "option_legalisation": "Apostille/Autenticazione",
        "option_legalisation_price": "49–129 € / doc",
        "option_assurance": "Consultazione per Assicurazioni",
        "option_assurance_price": "0 €",
        "option_rdv": "Consulenza/Appuntamento presenziale",
        "option_rdv_price": "49–149 €",
        "option_suivi": "SMS/Email status",
        "option_suivi_price": "Gratis in premium (oppure 49 €)",
        "included_title": "Che cosa è nel pacchetto",
        "conditions_title": "Condizioni",
        "condition1": "Costi Ambasciata son da calcolare.",
        "condition2": "Richiesta personale dell'individuo se necessaria dal VFS o Ambasciata."
    },
    "ja": {
        "meta": {
            "title": "料金とサービス タイビザ | 弊社 Siam Visa Pro",
            "description": "書類作成から大使館への提出まで一貫サポート。スタンダード、お急ぎ、プレミアムコースをご用意しております。"
        },
        "hero_title": "料金とサービス",
        "hero_subtitle": "書類作成・翻訳 ＋ 大使館提出",
        "hero_tagline": "面倒な手続きは私たちにお任せください。",
        "hero_tagline_secondary": "あなたのタイ移住を安心サポート。",
        "custom_support_title": "個別のサポートが必要ですか？",
        "custom_support_desc": "専門家がケースを詳しく分析し、最適なプランをご提案します。",
        "custom_support_btn": "専門家に相談",
        "tier_standard": "スタンダード",
        "tier_standard_desc": "書類作成 ＋ 申請サポート",
        "tier_standard_price": "390 €",
        "tier_express": "エクスプレス 48時間",
        "tier_express_desc": "書類作成 ＋ 緊急申請",
        "tier_express_price": "590 €",
        "tier_premium": "プレミアム",
        "tier_premium_desc": "書類作成 ＋ 申請 ＋ 優先サポート",
        "tier_premium_price": "890 €",
        "btn_start": "お申し込み",
        "recommended": "推奨",
        "insurance_title": "旅行保険 / 医療保険のご案内",
        "insurance_desc": "ビザの種類により保険加入が必須となるケースがございます。",
        "insurance_link": "提携保険会社",
        "pack_feat1": "資格審査と必要書類リスト",
        "pack_feat2": "各種フォームの準備と記入",
        "pack_feat3": "書類の詳細チェックと適合確認",
        "pack_feat4": "大使館へ提出する形式の整頓",
        "pack_feat5": "申請ならびにパスポート返却までの代行",
        "admin_fees_title": "政府・大使館の手数料",
        "admin_fees_subtitle": "別途かかります",
        "admin_fees_visa": "ビザ実費（各政府指定額）",
        "admin_fees_center": "申請センター手数料等",
        "options_title": "オプション",
        "option_traduction": "公式翻訳",
        "option_traduction_price": "39–89 € / 一部",
        "option_legalisation": "アポスティーユ等公証",
        "option_legalisation_price": "49–129 € / 一部",
        "option_assurance": "タイに適した保険サービス",
        "option_assurance_price": "0 € （自己申告）",
        "option_rdv": "面接等の予約サポート",
        "option_rdv_price": "49–149 €",
        "option_suivi": "最新状況の追跡",
        "option_suivi_price": "プレミアム無料 (通常 49 €)",
        "included_title": "各パッケージ内容",
        "conditions_title": "注意事項",
        "condition1": "政府への支払いは別途ご負担。",
        "condition2": "来館指定がある場合は同行サポート等を提供いたします。"
    },
    "ko": {
        "meta": {
            "title": "태국 비자 서비스 요금안내 | Siam Visa Pro",
            "description": "서류 준비부터 대사관 최종 심사까지 통합 제공. 등급별 서비스 요금을 확인하세요."
        },
        "hero_title": "서비스 및 요금",
        "hero_subtitle": "제반 서류 준비 + 대사관 최종 심사 지원",
        "hero_tagline": "안전하고 신뢰받는 여러분의 파트너",
        "hero_tagline_secondary": "여러분의 태국생활을 지원합니다.",
        "custom_support_title": "맞춤상담이 필요하십니까?",
        "custom_support_desc": "전문가가 여러분의 서류를 파악해 최적의 진행 일정을 세웁니다.",
        "custom_support_btn": "전문가와 상담",
        "tier_standard": "스탠다드",
        "tier_standard_desc": "서류준비 + 대사관 신청",
        "tier_standard_price": "390 €",
        "tier_express": "익스프레스 48시간",
        "tier_express_desc": "서류준비 + 긴급 신청",
        "tier_express_price": "590 €",
        "tier_premium": "프리미엄",
        "tier_premium_desc": "서류준비 + 신청 + 사후 밀착 모니터링",
        "tier_premium_price": "890 €",
        "btn_start": "지금 신청",
        "recommended": "추천 등급",
        "insurance_title": "의료보험 안내",
        "insurance_desc": "비자 요건상 일정 금액 이상의 생명/의료 보험이 필수입니다.",
        "insurance_link": "추천사 확인",
        "pack_feat1": "고객 적합성 심사",
        "pack_feat2": "신청서 작성대행",
        "pack_feat3": "필수 서류 누락 방지 체크",
        "pack_feat4": "완벽한 포맷의 심사제출물 정돈",
        "pack_feat5": "결과 확인 시까지 트래킹 지원",
        "admin_fees_title": "대사관 접수 비용",
        "admin_fees_subtitle": "대사관 실비 (개별 부담)",
        "admin_fees_visa": "태국 정부 지정 비자 심사 비용",
        "admin_fees_center": "비자센터 접수 대행료",
        "options_title": "추가 비용 옵션",
        "option_traduction": "번역 인증 서류",
        "option_traduction_price": "39–89 € / 장",
        "option_legalisation": "아포스티유 및 외교부 인증",
        "option_legalisation_price": "49–129 € / 장",
        "option_assurance": "태국 장기 체류 보험 연계",
        "option_assurance_price": "0 € (보험사 직결제)",
        "option_rdv": "오프라인 방문 예약",
        "option_rdv_price": "49–149 €",
        "option_suivi": "실시간 진행상황 조회 서비스",
        "option_suivi_price": "프리미엄 혜택(일반 49 € 추가)",
        "included_title": "공통 지원서비스",
        "conditions_title": "유의 사항",
        "condition1": "부결된 경우에도 환불 의무가 발생하지 않는 대사관 규정",
        "condition2": "직접 출석이 필요한 상황 등에 대한 안내 제공"
    },
    "ru": {
        "meta": {
            "title": "Услуги и Цены Виза в Таиланд | Siam Visa Pro",
            "description": "Сборка документов под ключ + подача в посольство. Пакеты: Стандарт, Экспресс, Премиум."
        },
        "hero_title": "Услуги и Цены",
        "hero_subtitle": "Полная подготовка документов + подача в посольство",
        "hero_tagline": "Мы ваш надежный партнер, а не консул.",
        "hero_tagline_secondary": "Опыт экспертов для вашего спокойствия в Таиланде.",
        "custom_support_title": "Нужна индивидуальная поддержка?",
        "custom_support_desc": "Наши эксперты помогут найти оптимальную стратегию релокации.",
        "custom_support_btn": "Связаться с экспертом",
        "tier_standard": "Стандарт",
        "tier_standard_desc": "Все документы + подача",
        "tier_standard_price": "390 €",
        "tier_express": "Экспресс 48ч",
        "tier_express_desc": "Все документы + срочная подача",
        "tier_express_price": "590 €",
        "tier_premium": "Премиум",
        "tier_premium_desc": "Документы + подача + VIP сопровождение",
        "tier_premium_price": "890 €",
        "btn_start": "Оформить заявку",
        "recommended": "Рекомендуем",
        "insurance_title": "Нужна туристическая страховка?",
        "insurance_desc": "Часто требуется полис минимум на 100 000 долларов.",
        "insurance_link": "Смотреть страховых брокеров",
        "pack_feat1": "Персональный чеклист и проверка",
        "pack_feat2": "Помощь с анкетами",
        "pack_feat3": "Аудит и ревью ваших бумаг",
        "pack_feat4": "Сборка в \"ready to embassy\" формат",
        "pack_feat5": "Отправка в посольство / консульство",
        "admin_fees_title": "Государственные сборы",
        "admin_fees_subtitle": "Оплачивается отдельно в МИД Таиланда",
        "admin_fees_visa": "Официальные сборы за визу",
        "admin_fees_center": "Сервисные и визовые центры",
        "options_title": "Дополнительные услуги",
        "option_traduction": "Аккредитованные переводы",
        "option_traduction_price": "39–89 € / документ",
        "option_legalisation": "Консульская легализация",
        "option_legalisation_price": "49–129 € / документ",
        "option_assurance": "Подбор медицинской страховки",
        "option_assurance_price": "0 € (оплата в страховую)",
        "option_rdv": "Переезд/запись",
        "option_rdv_price": "49–149 €",
        "option_suivi": "СМС и трекинг отправки",
        "option_suivi_price": "Бесплатно в Премиум (отдельно 49 €)",
        "included_title": "Включено в пакеты",
        "conditions_title": "Условия",
        "condition1": "Консульский и сервисный сбор не входят.",
        "condition2": "Сопровождение доступно при личной подаче."
    },
    "th": {
        "meta": {
            "title": "บริการและราคา รับทำวีซ่าไทย | Siam Visa Pro",
            "description": "เตรียมเอกสารและยื่นวีซ่า ราบรื่นไม่มีสะดุด มั่นใจในทุกการจัดการทั้ง Standard, Express และ Premium"
        },
        "hero_title": "บริการและราคาของเรา",
        "hero_subtitle": "จัดเตรียมเอกสารครบถ้วน + ยื่นเรื่องที่สถานทูต",
        "hero_tagline": "เราคือพันธมิตรที่พร้อมช่วยเหลือคุณเต็มที่",
        "hero_tagline_secondary": "ความเชี่ยวชาญของคุณ ที่คุณไว้วางใจได้",
        "custom_support_title": "ต้องการคำปรึกษาพิเศษหรือไม่?",
        "custom_support_desc": "ผู้เชี่ยวชาญของเราจะวิเคราะห์เคสอย่างละเอียดและเสนอแนวทางการย้ายถิ่นฐานที่ดีที่สุด",
        "custom_support_btn": "ปรึกษาผู้เชี่ยวชาญ",
        "tier_standard": "มาตรฐาน",
        "tier_standard_desc": "เตรียมเอกสารทั้งหมด + ยื่นผ่านสถานทูต",
        "tier_standard_price": "390 €",
        "tier_express": "ด่วนพิเศษ 48 ชม.",
        "tier_express_desc": "เตรียมเอกสารทั้งหมด + ยื่นด่วนฉับไว",
        "tier_express_price": "590 €",
        "tier_premium": "พรีเมียม VIP",
        "tier_premium_desc": "บริการตั้งต้นจนจบ พิเศษติดตามทุกระยะรับรองผลที่แน่นอนกว่า",
        "tier_premium_price": "890 €",
        "btn_start": "เริ่มต้นยื่นบริการ",
        "recommended": "แนะนำ",
        "insurance_title": "มองหาประกันภัยเดินทางเพิ่มเติมหรือไม่?",
        "insurance_desc": "เป็นระเบียบข้อบังคับจากสถานทูตไทยบางแห่ง (ความคุ้มครองขั้นต่ำที่ 100k USD)",
        "insurance_link": "เยี่ยมชมพาร์ทเนอร์ฝั่งประกัน",
        "pack_feat1": "วิเคราะห์การผ่านและไม่ผ่าน + ชุดเอกสารแบบปรับได้สำหรับ Case คุณ",
        "pack_feat2": "กรอกฟอร์มคำร้องทุกกระบวนการ",
        "pack_feat3": "พิจารณาข้อผิดพลาดและเอกสารตัวเสริมของลูกค้า",
        "pack_feat4": "จัดเรียงทำ Checklist สมบูรณ์พร้อมส่งต่อ",
        "pack_feat5": "บริการขนส่ง นำส่ง ต่อสถานราชการ",
        "admin_fees_title": "ค่าธรรมเนียมขอวีซ่าจากรัฐบาล",
        "admin_fees_subtitle": "ไม่รวมในราคางานบริการด้านบน",
        "admin_fees_visa": "จ่ายตรงตามลักษณะของวีซ่าที่คุณต้องการ",
        "admin_fees_center": "VFS ค่าอำนวยความสะดวกในแต่ละพื้นที่",
        "options_title": "บริการส่วนเสริมเพิ่มเติม",
        "option_traduction": "นักแปลได้รับการรับรองวิชาชีพแปล",
        "option_traduction_price": "39–89 € / ฉบับ",
        "option_legalisation": "กระบวนการให้สัตยาบัน และนิติกรณ์ตราประทับ",
        "option_legalisation_price": "49–129 € / ฉบับ",
        "option_assurance": "แนะนำแพ็คเกจประกันตรงเงื่อนไขรัฐบาลไทย",
        "option_assurance_price": "ฟรีไม่มีคิดเพิ่ม",
        "option_rdv": "คิวจองในระบบออนไลน์ หรือนำส่ง",
        "option_rdv_price": "49–149 €",
        "option_suivi": "Email อัปเดตสเตตัสอัตโนมัติ",
        "option_suivi_price": "สมาชิก VIP ฟรีปกติคิด 49 €",
        "included_title": "สิทธิที่คุณจะได้รับจากการใช้แพ็คเกจ",
        "conditions_title": "เงื่อนไขพึงทราบ",
        "condition1": "ไม่สามารถคืนเงินย้อนหลัง สำหรับค่าธรรมเนียมทุกประเภทที่ยื่นไปที่กระทรวงการต่างประเทศ",
        "condition2": "เราอาจจะขอนัดพาคอลหรือมีบริการนัดไปพร้อมกันให้สะดวกกว่า"
    },
    "zh": {
         "meta": {
            "title": "泰国签证代办 价格与服务指南 | Siam Visa Pro",
            "description": "提供完整的材料审核与大使馆递送。涵盖普通、急件和尊享加急等多层级服务价格。"
        },
        "hero_title": "服务与价格",
        "hero_subtitle": "完整文件准备 + 代客递签服务",
        "hero_tagline": "我们是您最可靠的泰国签证代理。",
        "hero_tagline_secondary": "为您的泰居之路保驾护航。",
        "custom_support_title": "找不到心仪的签证路线？",
        "custom_support_desc": "我们的签证专家可以仔细为您剖析各类政策并制定专属的合法落户方案。",
        "custom_support_btn": "与专家一对一沟通",
        "tier_standard": "标准套餐",
        "tier_standard_desc": "所有表单材料的起草整合＋递签",
        "tier_standard_price": "390 €",
        "tier_express": "48小时加急",
        "tier_express_desc": "最快响应制单＋使领馆紧急送签",
        "tier_express_price": "590 €",
        "tier_premium": "钻石尊享版",
        "tier_premium_desc": "完整材料准备＋领事馆递交＋人工时刻追踪",
        "tier_premium_price": "890 €",
        "btn_start": "现在注册申请",
        "recommended": "最高性价比",
        "insurance_title": "正在寻找出境旅行医疗保险？",
        "insurance_desc": "泰国政府对于特殊签证或时期会有硬性的十万美金报销项要求。",
        "insurance_link": "查阅本站保险合作商提供商",
        "pack_feat1": "在线评分及为您准备对应要求列表",
        "pack_feat2": "多语言表单填写与修正",
        "pack_feat3": "人工把关财务证明、照片护照的硬性规范",
        "pack_feat4": "编撰为高通过率的签证申请标准件",
        "pack_feat5": "领馆往返寄收业务及大使馆审批代表",
        "admin_fees_title": "领馆官方工本费用结算",
        "admin_fees_subtitle": "交给各辖区泰国使馆",
        "admin_fees_visa": "因国家区域或逗留长短而异的强制性官费",
        "admin_fees_center": "VFS中心驻地代收费（各地具体略有变动）",
        "options_title": "扩展支持业务",
        "option_traduction": "公证翻译／涉外翻译",
        "option_traduction_price": "39–89 € / 单张",
        "option_legalisation": "海牙认证 / 使馆认证",
        "option_legalisation_price": "49–129 € / 单张",
        "option_assurance": "外方保险直通渠道匹配",
        "option_assurance_price": "零中间商差价，官网直购结费",
        "option_rdv": "代客排队预约或亲赴代理",
        "option_rdv_price": "49–149 €",
        "option_suivi": "全透明进度追查与反馈",
        "option_suivi_price": "尊享版内免费包容，单独 49 €起",
        "included_title": "基础内嵌于各个礼包",
        "conditions_title": "法律条文",
        "condition1": "官费均为硬性收取且领馆存在拒签不退回制度。",
        "condition2": "涉及被特定使馆要求强制面签的情节，不适用全代理规则，需本人同行但可提供协助面谈环节。"
    }
}

for lang, data in translations.items():
    file_path = os.path.join(locales_dir, f"{lang}.ts")
    if not os.path.exists(file_path):
        continue
    
    with open(file_path, "r", encoding="utf-8") as file:
        content = file.read()
    
    # We will search for a meta or find the best place to insert "services_page": { ... }
    # Or replace it if it already exists
    
    services_page_content = ',\\n  "services_page": ' + json.dumps(data, indent=4, ensure_ascii=False)
    
    # Replace the existing one if it exists, otherwise add it before the last closing brace
    if '"services_page"' in content:
         # Use regex to replace the entire object if needed.
         # For safety, let's just do a rough replace.
         import re
         content = re.sub(r'(?m)^\s*"services_page"\s*:\s*\{[\s\S]*?(?<=\w)\},\s*$', '', content, flags=re.MULTILINE)
         content = re.sub(r'(?m)^\s*"services_page"\s*:\s*\{[\s\S]*?(?<=\w)\}\s*$', '', content, flags=re.MULTILINE)

    # Now append it before the very last closing brace.
    last_brace_index = content.rfind('}')
    if last_brace_index != -1:
        content = content[:last_brace_index] + services_page_content + '\n' + content[last_brace_index:]
        with open(file_path, "w", encoding="utf-8") as file:
            file.write(content)
        print(f"Patched {file_path}")
print("Completed patching")
