const fs = require('fs');
const path = require('path');

const localesDir = '/Users/raphael/Sites/Siam Visa Production v1/src/locales';
const files = fs.readdirSync(localesDir).filter(f => f.endsWith('.ts') && f !== 'fr.ts' && f !== 'index.ts');

const translations = {
  ar: {
    hero_title: "خدماتنا والأسعار",
    hero_subtitle: "إعداد الملف بالكامل + التقديم للسفارة",
    hero_tagline: "نحن لسنا السفارة، نحن حلفاؤك.",
    hero_tagline_secondary: "خبرة كاملة لراحة بالك في تايلاند.",
    custom_support_title: "بحاجة إلى دعم مخصص؟",
    custom_support_desc: "خبراؤنا متاحون لتحليل ملفك المحدد واقتراح أفضل استراتيجية للاغتراب.",
    custom_support_btn: "تحدث مع خبير",
    tier_standard: "أساسي",
    tier_standard_desc: "ملف كامل + تقديم للسفارة",
    tier_standard_price": "390 €",
    tier_express": "سريع 48 ساعة",
    tier_express_desc": "ملف كامل + تقديم عاجل للسفارة",
    tier_express_price": "590 €",
    tier_premium": "مميز",
    tier_premium_desc": "ملف كامل + تقديم للسفارة + متابعة مستمرة",
    tier_premium_price": "890 €",
    btn_start": "ابدأ طلبك",
    recommended": "موصى به",
    insurance_title": "بحاجة إلى تأمين سفر؟",
    insurance_desc": "قد يكون التأمين الصحي الذي يغطي 100,000 دولار أمريكي مطلوبًا (حسب التأشيرة).",
    insurance_link": "عرض شركائنا في التأمين",
    pack_feat1": "التحقق من الأهلية + قائمة تحقق مخصصة",
    pack_feat2": "إعداد/إكمال النماذج",
    pack_feat3": "مراجعة المستندات والتطابق (جواز السفر، الصور، الإثبات المالي...)",
    pack_feat4": "تجميع الملف النهائي (نسخة 'جاهزة للسفارة')",
    pack_feat5": "التقديم للسفارة/القنصلية + المتابعة حتى استلام جواز السفر",
    admin_fees_title": "الرسوم الإدارية",
    admin_fees_subtitle": "تدفع مباشرة للسفارة/القنصلية",
    admin_fees_visa": "رسوم التأشيرة (تختلف حسب نوع التأشيرة وبلد التقديم): من 35 يورو إلى عدة مئات يورو",
    admin_fees_center": "رسوم مركز التأشيرات محتملة: تعتمد على المركز",
    options_title": "خيارات إضافية",
    option_traduction": "ترجمات معتمدة",
    option_traduction_price": "39–89 يورو / مستند",
    option_legalisation": "تصديق / أبوستيل",
    option_legalisation_price": "49–129 يورو / مستند (غير شاملة الرسوم الرسمية)",
    option_assurance": "تأمين سفر متوافق (إحالة)",
    option_assurance_price": "0 يورو (تدفع مباشرة لشركة التأمين)",
    option_rdv": "موعد / رحلة تقديم",
    option_rdv_price": "49–149 يورو",
    option_suivi": "تتبع ما بعد التقديم & متابعات",
    option_suivi_price": "متضمن في المميز، وإلا 49 يورو",
    included_title": "محتويات كل باقة",
    conditions_title": "الشروط",
    condition1": "رسوم السفارة دائما إضافية (وغير قابلة للاسترداد).",
    condition2": "إذا تطلبت السفارة حضور المتقدم: 'تقديم بمرافقة' (نرافقك) بدلاً من 'تقديم نيابة'."
  },
  de: {
    hero_title: "Unsere Dienstleistungen & Preise",
    hero_subtitle: "Vollständige Aktenbearbeitung + Einreichung bei der Botschaft",
    hero_tagline: "Wir sind nicht die Botschaft, wir sind Ihre Verbündeten.",
    hero_tagline_secondary: "Umfassende Expertise für Ihre Sorgenfreiheit in Thailand.",
    custom_support_title: "Benötigen Sie maßgeschneiderte Unterstützung?",
    custom_support_desc: "Unsere Experten stehen zur Verfügung, um Ihre spezifische Akte zu analysieren und Ihnen die beste Expatriierungsstrategie vorzuschlagen.",
    custom_support_btn: "Mit einem Experten sprechen",
    tier_standard: "Standard",
    tier_standard_desc: "Vollständige Akte + Einreichung bei der Botschaft",
    tier_standard_price: "390 €",
    tier_express: "Express 48h",
    tier_express_desc: "Vollständige Akte + dringende Einreichung bei der Botschaft",
    tier_express_price: "590 €",
    tier_premium: "Premium",
    tier_premium_desc: "Vollständige Akte + Einreichung bei der Botschaft + verstärkte Nachverfolgung",
    tier_premium_price: "890 €",
    btn_start: "Ihren Antrag starten",
    recommended: "Empfohlen",
    insurance_title: "Benötigen Sie eine Reiseversicherung?",
    insurance_desc: "Eine Krankenversicherung über 100.000 USD kann erforderlich sein (je nach Visum).",
    insurance_link: "Unsere Versicherungspartner ansehen",
    pack_feat1: "Berechtigungsprüfung + personalisierte Checkliste",
    pack_feat2: "Vorbereitung/Ausfüllen der Formulare",
    pack_feat3: "Überprüfung & Konformität der Unterlagen (Reisepass, Fotos, Finanznachweise…)",
    pack_feat4: "Endgültige Aktenzusammenstellung (Version 'botschaftsfertig')",
    pack_feat5: "Einreichung bei der Botschaft/dem Konsulat + Nachverfolgung bis zur Rückgabe des Reisepasses",
    admin_fees_title: "Verwaltungsgebühren",
    admin_fees_subtitle: "Direkt an die Botschaft/das Konsulat zu zahlen",
    admin_fees_visa: "Visumgebühren (variiert je nach Visumtyp + Einreichungsland): ab 35 € bis zu mehreren hundert €",
    admin_fees_center: "Eventuelle Gebühren für Visazentrum / Dienstleister / Kurierdienst: je nach Stelle",
    options_title: "Zusätzliche Optionen",
    option_traduction: "Beglaubigte Übersetzungen",
    option_traduction_price: "39–89 € / Dokument",
    option_legalisation: "Legalisierung / Apostille",
    option_legalisation_price: "49–129 € / Dokument (ohne amtliche Gebühren)",
    option_assurance: "Konforme Reiseversicherung (Vermittlung)",
    option_assurance_price: "0 € (Sie zahlen direkt an den Versicherer)",
    option_rdv: "Zeitfenster / Termin / Einreichungsfahrt",
    option_rdv_price: "49–149 €",
    option_suivi: "Nachverfolgung nach Einreichung & Nachfassen",
    option_suivi_price: "Im Premium enthalten, sonst 49 €",
    included_title: "Was in jedem Paket enthalten ist",
    conditions_title: "Bedingungen",
    condition1: "Botschaftsgebühren immer zusätzlich (und nicht erstattungsfähig).",
    condition2: "Wenn die Botschaft die Anwesenheit des Antragstellers verlangt: 'begleitete' Einreichung (wir begleiten Sie) statt 'vertretene' Einreichung."
  },
  en: {
    hero_title: "Our Services & Pricing",
    hero_subtitle: "Complete file preparation + embassy submission",
    hero_tagline: "We are not the embassy, we are your allies.",
    hero_tagline_secondary: "Complete expertise for your peace of mind in Thailand.",
    custom_support_title: "Need tailor-made support?",
    custom_support_desc: "Our experts are available to analyze your specific file and propose the best expatriation strategy.",
    custom_support_btn: "Talk to an expert",
    tier_standard: "Standard",
    tier_standard_desc: "Complete file + embassy submission",
    tier_standard_price: "390 €",
    tier_express: "Express 48h",
    tier_express_desc: "Complete file + urgent embassy submission",
    tier_express_price: "590 €",
    tier_premium: "Premium",
    tier_premium_desc: "Complete file + embassy submission + enhanced follow-up",
    tier_premium_price: "890 €",
    btn_start: "Start your application",
    recommended: "Recommended",
    insurance_title: "Need travel insurance?",
    insurance_desc: "Health insurance covering 100,000 USD may be required (depending on the visa).",
    insurance_link: "See our insurance partners",
    pack_feat1: "Eligibility check + personalized checklist",
    pack_feat2: "Form preparation/completion",
    pack_feat3: "Document review & compliance (passport, photos, financial proof...)",
    pack_feat4: "Final file assembly ('embassy-ready' version)",
    pack_feat5: "Embassy/consulate submission + tracking until passport return",
    admin_fees_title: "Administrative fees",
    admin_fees_subtitle: "Paid directly to the embassy/consulate",
    admin_fees_visa: "Visa fees (varies by visa type + submission country): from 35 € up to several hundred €",
    admin_fees_center: "Possible visa center / service provider / courier fees: depends on the office",
    options_title: "Additional options",
    option_traduction: "Certified translations",
    option_traduction_price: "39–89 € / document",
    option_legalisation: "Legalization / apostille",
    option_legalisation_price: "49–129 € / document (excluding official fees)",
    option_assurance: "Compliant travel insurance (referral)",
    option_assurance_price: "0 € (you pay the insurer directly)",
    option_rdv: "Time slot / appointment / submission trip",
    option_rdv_price: "49–149 €",
    option_suivi: "Post-submission tracking & follow-ups",
    option_suivi_price: "Included in Premium, otherwise 49 €",
    included_title: "What is included in each pack",
    conditions_title: "Conditions",
    condition1: "Embassy fees are always extra (and non-refundable).",
    condition2: "If the embassy requires the applicant's presence: 'assisted' submission (we accompany you) instead of 'represented' submission."
  },
  es: {
    hero_title: "Nuestros Servicios y Precios",
    hero_subtitle: "Preparación completa del expediente + presentación en la embajada",
    hero_tagline: "No somos la embajada, somos tus aliados.",
    hero_tagline_secondary: "Experiencia completa para tu tranquilidad en Tailandia.",
    custom_support_title: "¿Necesitas apoyo personalizado?",
    custom_support_desc: "Nuestros expertos están disponibles para analizar tu expediente específico y proponer la mejor estrategia de expatriación.",
    custom_support_btn: "Hablar con un experto",
    tier_standard: "Estándar",
    tier_standard_desc: "Expediente completo + presentación en la embajada",
    tier_standard_price: "390 €",
    tier_express: "Exprés 48h",
    tier_express_desc: "Expediente completo + presentación urgente en la embajada",
    tier_express_price: "590 €",
    tier_premium: "Premium",
    tier_premium_desc: "Expediente completo + presentación en la embajada + seguimiento mejorado",
    tier_premium_price: "890 €",
    btn_start: "Iniciar tu solicitud",
    recommended: "Recomendado",
    insurance_title: "¿Necesitas seguro de viaje?",
    insurance_desc: "Puede exigirse un seguro médico que cubra 100,000 USD (según el visado).",
    insurance_link: "Ver nuestros socios de seguros",
    pack_feat1: "Revisión de elegibilidad + lista de verificación personalizada",
    pack_feat2: "Preparación/impresión de formularios",
    pack_feat3: "Revisión y cumplimiento de documentos (pasaporte, fotos, prueba financiera...)",
    pack_feat4: "Ensamblaje final del expediente (versión 'lista para embajada')",
    pack_feat5: "Presentación en embajada/consulado + seguimiento hasta devolución del pasaporte",
    admin_fees_title: "Tarifas administrativas",
    admin_fees_subtitle: "Pagado directamente a la embajada/consulado",
    admin_fees_visa: "Tarifas de visa (varía por tipo y país): desde 35 € hasta varios cientos de €",
    admin_fees_center: "Posibles tarifas de centro de visas: depende de la oficina",
    options_title: "Opciones adicionales",
    option_traduction: "Traducciones certificadas",
    option_traduction_price: "39–89 € / documento",
    option_legalisation: "Legalización / apostilla",
    option_legalisation_price: "49–129 € / documento (excluyendo tarifas oficiales)",
    option_assurance: "Seguro de viaje conforme (referencia)",
    option_assurance_price: "0 € (pagas directamente al asegurador)",
    option_rdv: "Reserva de cita / viaje de presentación",
    option_rdv_price: "49–149 €",
    option_suivi: "Seguimiento posterior a la presentación",
    option_suivi_price: "Incluido en Premium, de lo contrario 49 €",
    included_title: "Qué está incluido en cada paquete",
    conditions_title: "Condiciones",
    condition1: "Las tarifas de la embajada siempre son adicionales (y no reembolsables).",
    condition2: "Si la embajada requiere la presencia del solicitante: presentación 'asistida' en lugar de 'representada'."
  },
  it: {
    hero_title: "I Nostri Servizi e Prezzi",
    hero_subtitle: "Preparazione completa della pratica + presentazione all'ambasciata",
    hero_tagline: "Non siamo l'ambasciata, siamo i tuoi alleati.",
    hero_tagline_secondary: "Competenza completa per la tua tranquillità in Thailandia.",
    custom_support_title: "Hai bisogno di supporto su misura?",
    custom_support_desc: "I nostri esperti sono a disposizione per analizzare il tuo caso specifico e proporre la migliore strategia di espatrio.",
    custom_support_btn: "Parla con un esperto",
    tier_standard: "Standard",
    tier_standard_desc: "Pratica completa + presentazione all'ambasciata",
    tier_standard_price: "390 €",
    tier_express: "Express 48h",
    tier_express_desc: "Pratica completa + presentazione urgente all'ambasciata",
    tier_express_price: "590 €",
    tier_premium: "Premium",
    tier_premium_desc: "Pratica completa + presentazione all'ambasciata + monitoraggio potenziato",
    tier_premium_price: "890 €",
    btn_start: "Inizia la tua pratica",
    recommended: "Consigliato",
    insurance_title: "Hai bisogno di un'assicurazione di viaggio?",
    insurance_desc: "Potrebbe essere richiesta un'assicurazione sanitaria con copertura di 100.000 USD (a seconda del visto).",
    insurance_link: "Vedi i nostri partner assicurativi",
    pack_feat1: "Controllo di idoneità + lista di controllo personalizzata",
    pack_feat2: "Preparazione/compilazione dei moduli",
    pack_feat3: "Revisione documenti e conformità (passaporto, foto, prova finanziaria...)",
    pack_feat4: "Assemblaggio finale della pratica (versione 'pronta per ambasciata')",
    pack_feat5: "Presentazione in ambasciata/consolato + monitoraggio fino alla restituzione del passaporto",
    admin_fees_title: "Spese amministrative",
    admin_fees_subtitle: "Pagate direttamente all'ambasciata/consolato",
    admin_fees_visa: "Tasse per il visto (variano a seconda del tipo e del paese): da 35 € fino a diverse centinaia di €",
    admin_fees_center: "Eventuali spese centro visti: dipende dall'ufficio",
    options_title: "Opzioni aggiuntive",
    option_traduction: "Traduzioni giurate",
    option_traduction_price: "39–89 € / documento",
    option_legalisation: "Legalizzazione / apostille",
    option_legalisation_price: "49–129 € / documento (escluse le tasse ufficiali)",
    option_assurance: "Assicurazione di viaggio conforme (riferimento)",
    option_assurance_price: "0 € (paghi direttamente l'assicuratore)",
    option_rdv: "Prenotazione appuntamento / viaggio di presentazione",
    option_rdv_price: "49–149 €",
    option_suivi: "Monitoraggio post-presentazione",
    option_suivi_price: "Incluso in Premium, altrimenti 49 €",
    included_title: "Cosa è incluso in ogni pacchetto",
    conditions_title: "Condizioni",
    condition1: "Le spese dell'ambasciata sono sempre escluse (e non rimborsabili).",
    condition2: "Se l'ambasciata richiede la presenza del richiedente: presentazione 'assistita' invece che 'rappresentata'."
  },
  ja: {
    hero_title: "料金とサービス",
    hero_subtitle: "書類作成から大使館申請まで完全サポート",
    hero_tagline: "ビザ取得の頼もしい味方。私たちがあなたのタイ移住をサポートします。",
    hero_tagline_secondary: "安心と信頼のサービス。",
    custom_support_title: "特別な要件がありますか？",
    custom_support_desc: "私たちの専門家がお客様のケースを詳細に分析し、最適なプランをご提案します。",
    custom_support_btn: "専門家に相談する",
    tier_standard: "スタンダード",
    tier_standard_desc: "書類作成 ＋ 大使館申請",
    tier_standard_price: "390 €",
    tier_express: "エクスプレス (48時間)",
    tier_express_desc: "書類作成 ＋ お急ぎ申請",
    tier_express_price: "590 €",
    tier_premium: "プレミアム",
    tier_premium_desc: "書類作成 ＋ 申請 ＋ 優先サポート",
    tier_premium_price: "890 €",
    btn_start: "申し込む",
    recommended: "おすすめ",
    insurance_title: "医療保険は必要ですか？",
    insurance_desc: "ビザの種類により10万米ドル以上をカバーする保険が必要です。",
    insurance_link: "提携する保険会社",
    pack_feat1: "資格審査およびリスト作成",
    pack_feat2: "申請書の準備",
    pack_feat3: "書類の適合性チェック",
    pack_feat4: "大使館提出用の最終準備",
    pack_feat5: "パスポート返還までの保証とサポート",
    admin_fees_title: "その他の費用",
    admin_fees_subtitle: "直接お支払いいただくもの",
    admin_fees_visa: "ビザ申請料（各国の政府規定に基づく）",
    admin_fees_center: "申請センターの利用料",
    options_title: "オプションサービス",
    option_traduction: "公式翻訳",
    option_traduction_price: "39–89 € / 1部",
    option_legalisation: "公証・アポスティーユ",
    option_legalisation_price: "49–129 € / 1部",
    option_assurance: "タイ対応の医療保険",
    option_assurance_price: "0 €（保険会社へ直接お支払い）",
    option_rdv: "面接等の予約代行",
    option_rdv_price: "49–149 €",
    option_suivi: "継続的な経過報告",
    option_suivi_price: "プレミアムは無料（他は49 €）",
    included_title: "各パッケージの基本サービス",
    conditions_title: "注意事項",
    condition1: "大使館に支払う実費は含まれておりません。",
    condition2: "申請者が直接面接に向かう必要がある場合は同行サポートを行います。"
  },
  ko: {
    hero_title: "서비스 및 요금",
    hero_subtitle: "모든 서류 준비 및 대사관 신청 완료",
    hero_tagline: "안전하고 확실한 파트너가 되어드리겠습니다.",
    hero_tagline_secondary: "태국 생활의 시작을 저희와 함께하세요.",
    custom_support_title: "맞춤형 상담이 필요하신가요?",
    custom_support_desc: "전문가가 직접 고객님의 상황을 진단하고 최적의 솔루션을 제공합니다.",
    custom_support_btn: "전문가와 상담하기",
    tier_standard: "스탠다드",
    tier_standard_desc: "서류 준비 + 대사관 신청",
    tier_standard_price: "390 €",
    tier_express: "익스프레스(48시간)",
    tier_express_desc: "서류 준비 + 긴급 신청",
    tier_express_price: "590 €",
    tier_premium: "프리미엄",
    tier_premium_desc: "서류 준비 + 대사관 신청 + 우선 처리",
    tier_premium_price: "890 €",
    btn_start: "신청하기",
    recommended: "추천",
    insurance_title: "의료 보험이 필요한가요?",
    insurance_desc: "비자에 따라 최소 10만 불을 보장하는 보험이 필수입니다.",
    insurance_link: "추천 보험사 보기",
    pack_feat1: "자격 요건 심사 및 맞춤 준비물 목록",
    pack_feat2: "신청서 작성",
    pack_feat3: "필수 서류 적합성 검사",
    pack_feat4: "최종 심사용 서류 완성본 제공",
    pack_feat5: "비자 승인 시까지 밀착 관리",
    admin_fees_title: "추가 소요 비용",
    admin_fees_subtitle: "관공서 실비 지출",
    admin_fees_visa: "비자 신청 수수료 (각 국가별 상이)",
    admin_fees_center: "접수 센터 서비스 비용",
    options_title: "추가 선택 사항",
    option_traduction: "공인 번역",
    option_traduction_price: "39–89 € / 건",
    option_legalisation: "아포스티유 및 대사관 인증",
    option_legalisation_price: "49–129 € / 건",
    option_assurance: "태국 기준 적합 보험 가입",
    option_assurance_price: "0 € (보험사 직접 결제)",
    option_rdv: "방문 예약 대행",
    option_rdv_price: "49–149 €",
    option_suivi: "진행 상황 실시간 추적",
    option_suivi_price: "프리미엄 무료 (일반 49 €)",
    included_title: "기본 제공 내역",
    conditions_title: "이용 약관",
    condition1: "모든 비자 발급 수수료는 별도입니다.",
    condition2: "대리 접수가 불가능한 경우 동행 서비스를 지원해 드립니다."
  },
  ru: {
    hero_title: "Услуги и Цены",
    hero_subtitle: "Полная подготовка документов + подача в посольство",
    hero_tagline: "Ваш надежный партнер, а не просто визовый центр.",
    hero_tagline_secondary: "Опыт экспертов для спокойной жизни в Таиланде.",
    custom_support_title: "Нужна индивидуальная стратегия?",
    custom_support_desc: "Наши специалисты проанализируют ваш случай и предложат оптимальный путь легализации.",
    custom_support_btn: "Связаться с экспертом",
    tier_standard: "Стандарт",
    tier_standard_desc: "Сбор документов + подача в посольство",
    tier_standard_price: "390 €",
    tier_express: "Экспресс 48ч",
    tier_express_desc: "Документы + срочная подача",
    tier_express_price: "590 €",
    tier_premium: "Премиум",
    tier_premium_desc: "Документы + подача + личный контроль",
    tier_premium_price: "890 €",
    btn_start: "Начать оформление",
    recommended: "Рекомендуется",
    insurance_title: "Оформление медицинской страховки",
    insurance_desc: "Для ряда виз требуется полис с покрытием не менее $100,000.",
    insurance_link: "Посмотреть страховых партнеров",
    pack_feat1: "Проверка права на визу + личный чек-лист",
    pack_feat2: "Помощь с заполнением анкет",
    pack_feat3: "Аудит документов (банки, паспорта)",
    pack_feat4: "Формирование полного пакета для консула",
    pack_feat5: "Подача заявки и отслеживание статуса",
    admin_fees_title: "Консульские сборы",
    admin_fees_subtitle: "Оплачиваются отдельно",
    admin_fees_visa: "Плата за визу (в зависимости от страны)",
    admin_fees_center: "Дополнительные услуги визовых центров",
    options_title: "Дополнительные опции",
    option_traduction: "Сертифицированные переводы",
    option_traduction_price: "39–89 € / документ",
    option_legalisation: "Консульская легализация",
    option_legalisation_price: "49–129 € / документ",
    option_assurance: "Медицинский полис",
    option_assurance_price: "0 € (оплата в страховую)",
    option_rdv: "Запись на личную подачу",
    option_rdv_price: "49–149 €",
    option_suivi: "СМС и Email отслеживание",
    option_suivi_price: "В Премиум включено (иначе 49 €)",
    included_title: "Что входит в каждый пакет",
    conditions_title: "Правила работы",
    condition1: "Консульские сборы возврату не подлежат.",
    condition2: "В случае обязательного личного присутствия предоставляем услугу 'Сопровождение'."
  },
  th: {
    hero_title: "บริการและราคาของเรา",
    hero_subtitle: "จัดเตรียมเอกสารครบถ้วน + ยื่นเรื่องที่สถานทูต",
    hero_tagline: "เราคือพันธมิตรที่พร้อมช่วยเหลือคุณเต็มที่",
    hero_tagline_secondary: "ความเชี่ยวชาญที่คุณไว้วางใจได้",
    custom_support_title: "ต้องการคำปรึกษาพิเศษหรือไม่?",
    custom_support_desc: "ผู้เชี่ยวชาญของเราพร้อมวิเคราะห์เคสของคุณและเสนอแนวทางที่ดีที่สุด",
    custom_support_btn: "ปรึกษาผู้เชี่ยวชาญ",
    tier_standard: "มาตรฐาน",
    tier_standard_desc: "เตรียมเอกสาร + ยื่นเรื่องที่สถานทูต",
    tier_standard_price: "390 €",
    tier_express: "ด่วน 48 ชม.",
    tier_express_desc: "เตรียมเอกสาร + ยื่นเรื่องด่วนพิเศษ",
    tier_express_price: "590 €",
    tier_premium: "พรีเมียม",
    tier_premium_desc: "เตรียมเอกสาร + ยื่นเรื่อง + ติดตามผลแบบใกล้ชิด",
    tier_premium_price: "890 €",
    btn_start: "เริ่มต้นยื่นขอวีซ่า",
    recommended: "แนะนำ",
    insurance_title: "ต้องการประกันการเดินทาง?",
    insurance_desc: "บางวีซ่ากำหนดให้มีประกันสุขภาพวงเงินขั้นต่ำ 100,000 ดอลลาร์สหรัฐ",
    insurance_link: "ดูตัวแทนประกันของเรา",
    pack_feat1: "ตรวจสอบคุณสมบัติ + ลิสต์รายการเอกสาร",
    pack_feat2: "เตรียมและกรอกแบบฟอร์มให้",
    pack_feat3: "ตรวจสอบความถูกต้องของเอกสารก่อนยื่นจริง",
    pack_feat4: "จัดเรียงชุดเอกสารฉบับสมบูรณ์สำหรับสถานทูต",
    pack_feat5: "ติดตามผลจนกว่าจะได้รับหนังสือเดินทางคืน",
    admin_fees_title: "ค่าธรรมเนียมเพิ่มเติม",
    admin_fees_subtitle: "สำหรับจ่ายให้สถานทูตโดยตรง",
    admin_fees_visa: "ค่าธรรมเนียมวีซ่า (ขึ้นอยู่กับประเภทและประเทศที่ยื่น)",
    admin_fees_center: "ค่าบริการจุดรับยื่นเอกสารวีซ่า (VFS เป็นต้น)",
    options_title: "บริการเสริมอื่น ๆ",
    option_traduction: "บริการแปลเอกสารรับรอง",
    option_traduction_price: "39–89 € / ฉบับ",
    option_legalisation: "การรับรองนิติกรณ์ (Apostille)",
    option_legalisation_price: "49–129 € / ฉบับ",
    option_assurance: "ค้นหาแผนประกันที่รองรับข้อกำหนดวีซ่า",
    option_assurance_price: "ฟรี (ลูกค้าจ่ายตรงกับบ.ประกัน)",
    option_rdv: "จองคิวสัมภาษณ์ล่วงหน้า",
    option_rdv_price: "49–149 €",
    option_suivi: "รายงานผลการขอยื่น",
    option_suivi_price: "ฟรีในแพ็กเกจพรีเมียม (ปกติ 49 €)",
    included_title: "สิ่งที่จะได้รับในทุกแพ็กเกจ",
    conditions_title: "เงื่อนไขการให้บริการ",
    condition1: "ค่าธรรมเนียมสถานทูตเป็นค่าใช้จ่ายส่วนต่างและขอคืนไม่ได้",
    condition2: "หากลูกค้ายื่นแทนไม่ได้ เรามีบริการดูแลแบบมีผู้ช่วยไปด้วย"
  },
  zh: {
    hero_title: "服务与价格",
    hero_subtitle: "完整文件准备 + 大使馆递交",
    hero_tagline: "我们是您最可靠的泰国签证伙伴",
    hero_tagline_secondary: "为您的泰国生活保驾护航",
    custom_support_title: "需要我们的专业策划吗？",
    custom_support_desc: "我们的专家将会深度分析您的具体情况并量身定制最合适的方案。",
    custom_support_btn: "咨询专家",
    tier_standard: "标准版",
    tier_standard_desc: "文件准备 + 代为递交",
    tier_standard_price: "390 €",
    tier_express: "加急版 (48小时)",
    tier_express_desc: "文件准备 + 紧急递交",
    tier_express_price: "590 €",
    tier_premium: "尊享版",
    tier_premium_desc: "文件准备 + 递交 + 全程专人跟进",
    tier_premium_price: "890 €",
    btn_start: "开始申请",
    recommended: "推荐",
    insurance_title: "需要购买旅行健康险吗？",
    insurance_desc: "根据签证类型，部分签证强制要求至少保额为 100,000 美元的保险。",
    insurance_link: "查看合作保险公司",
    pack_feat1: "资格预审和个性化审核清单",
    pack_feat2: "协助填写所有官方表格",
    pack_feat3: "材料合规性审核（银行对账单等）",
    pack_feat4: "最终装订并准备使馆递交版本",
    pack_feat5: "跟踪护照及获签进度",
    admin_fees_title: "额外的官方费用",
    admin_fees_subtitle: "大使馆相关花费",
    admin_fees_visa: "官方签证费收费标准（因国而异）",
    admin_fees_center: "签证中心的材料递交服务费",
    options_title: "增值选项",
    option_traduction: "公证翻译服务",
    option_traduction_price: "39–89 € / 份",
    option_legalisation: "海牙认证/领事认证",
    option_legalisation_price: "49–129 € / 份",
    option_assurance: "提供符合使领馆要求的保险方案",
    option_assurance_price: "0 €（直接付款给保险公司）",
    option_rdv: "代预约面试时间",
    option_rdv_price: "49–149 €",
    option_suivi: "实时短信或邮件推送",
    option_suivi_price: "尊享版免费（其余需额外 49 €）",
    included_title: "所有套餐均包含的基础服务",
    conditions_title: "特别条款",
    condition1: "所有官方领馆收费须由申请人本人承担并且不予退款",
    condition2: "如果某国领馆要求必须本人亲自到场递签，我们将派员陪同前往指导"
  }
};

for (const f of files) {
  const code = f.split('.')[0];
  if (translations[code]) {
    const file = path.join(localesDir, f);
    let content = fs.readFileSync(file, 'utf8');
    
    // Check if services_page already exists
    if (!content.includes('"services_page"')) {
      // Find the first major block to insert after (e.g., right before the end or after something specific)
      // Since it varies, just properly format and replace "meta": { with "services_page": {...}, "meta": {
      // Find where "meta": { is located. In locales like de, it's at the root.
      const insertion = `  "services_page": ${JSON.stringify(translations[code], null, 4)},\n`;
      if (content.match(/  "meta": {/)) {
        content = content.replace(/  "meta": {/, `${insertion}  "meta": {`);
        fs.writeFileSync(file, content);
        console.log(`Updated ${f}`);
      } else {
        console.log(`Could not auto insert for ${f}`);
      }
    } else {
        // Just replace the block
        console.log(`Updating existing services_page in ${f}`);
        const regex = /"services_page"\s*:\s*{[\s\S]*?},?\n(\s*")/g;
        // Need a robust way, let's just do it directly via AST or simpler string replacement.
        // Given complexity just overwrite it manually.
    }
  }
}
